# hyprscroller
plugin {
    scroller {
        fullscreen_on_one_column = true
        column_widths = onethird onehalf twothirds one
        window_heights = onethird onehalf twothirds one
    }
}
bind = Alt,P,scroller:jump
bind = $mainMod,F,scroller:fitsize,all
# bind = Alt,P,scroller:trailprevious
bind = $mainMod Alt, W, scroller:cyclewidth, next
bind = $mainMod Alt, H, scroller:cycleheight, next

bind =$mainMod Shift,H,scroller:admitwindow,left
bind =$mainMod Shift,L,scroller:admitwindow,right

bind = $mainMod, J, scroller:setmode, c
bind = $mainMod, K, scroller:setmode, r
bind = Alt,I,scroller:expelwindow

# bind = $mainMod SHIFT, H, togglespecialworkspace, 3
# bind = $mainMod, H, exec, pypr toggle_special 3
