-- Generated by nwg-displays on 2026-05-13 at 22:59:50. Do not edit manually.
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.06", position = "-1x-1", scale = 1.0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.0", position = "0x1080", scale = 1.0 })
