[urgency_low]
    background = "#8D65A380"
    foreground = "#EDCCFFE6"
    frame_color = "#8D65A303"
    icon = "$HOME/.config/dunst/icons/clock-fast.svg"
    timeout = 5

[urgency_normal]
    background = "#553A6B80"
    foreground = "#E9CCFFE6"
    frame_color = "#553A6B03"
    icon = "$HOME/.config/dunst/icons/clock-fast.svg"
    timeout = 5
