
[urgency_low]
    background = "#A38C6580"
    foreground = "#FFECCCE6"
    frame_color = "#A38C6503"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A686B80"
    foreground = "#CCFCFFE6"
    frame_color = "#3A686B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
