
[urgency_low]
    background = "#658AA380"
    foreground = "#CCEAFFE6"
    frame_color = "#658AA303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3C3A6B80"
    foreground = "#CECCFFE6"
    frame_color = "#3C3A6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
