#!/bin/bash

# Directory where system sounds are stored
sound_dir="/usr/share/sounds/freedesktop/stereo"

# Directory where icons are stored
icon_dir="/home/nirantar/.config/dunst/icons"
random_icon_dir="$icon_dir/random"

# Declare an associative array of sound options
declare -A sounds=(
    [alarm-clock-elapsed]="alarm-clock-elapsed.oga"
    [audio-channel-front-center]="audio-channel-front-center.oga"
    [audio-channel-front-left]="audio-channel-front-left.oga"
    [audio-channel-front-right]="audio-channel-front-right.oga"
    [audio-channel-rear-center]="audio-channel-rear-center.oga"
    [audio-channel-rear-left]="audio-channel-rear-left.oga"
    [audio-channel-rear-right]="audio-channel-rear-right.oga"
    [audio-channel-side-left]="audio-channel-side-left.oga"
    [audio-channel-side-right]="audio-channel-side-right.oga"
    [audio-test-signal]="audio-test-signal.oga"
    [audio-volume-change]="audio-volume-change.oga"
    [bell]="bell.oga"
    [camera-shutter]="camera-shutter.oga"
    [complete]="complete.oga"
    [device-added]="device-added.oga"
    [device-removed]="device-removed.oga"
    [dialog-error]="dialog-error.oga"
    [dialog-information]="dialog-information.oga"
    [dialog-warning]="dialog-warning.oga"
    [message-new-instant]="message-new-instant.oga"
    [message]="message.oga"
    [network-connectivity-established]="network-connectivity-established.oga"
    [network-connectivity-lost]="network-connectivity-lost.oga"
    [phone-incoming-call]="phone-incoming-call.oga"
    [phone-outgoing-busy]="phone-outgoing-busy.oga"
    [phone-outgoing-calling]="phone-outgoing-calling.oga"
    [power-plug]="power-plug.oga"
    [power-unplug]="power-unplug.oga"
    [screen-capture]="screen-capture.oga"
    [service-login]="service-login.oga"
    [service-logout]="service-logout.oga"
    [suspend-error]="suspend-error.oga"
    [trash-empty]="trash-empty.oga"
    [window-attention]="window-attention.oga"
    [window-question]="window-question.oga"
)

urgency="normal"
message=""
sound_key=""
sound_file=""
icon_path=""
app_name="custom-notify"
replace_id=12345
notify_extra_opts=""

# Parse command line
while [[ $# -gt 0 ]]; do
    case "$1" in
        -low) urgency="low"; shift ;;
        -normal) urgency="normal"; shift ;;
        -critical) urgency="critical"; shift ;;
        --message)
            message="$2"
            shift 2
            ;;
        --app-name)
            app_name="$2"
            shift 2
            ;;
        --replace-id)
            replace_id="$2"
            shift 2
            ;;
        --notify-opts)
            notify_extra_opts="$2"
            shift 2
            ;;
        --icon)
            icon_path="$2"
            shift 2
            ;;
        -*)  # sound key
            sound_key="${1#-}"
            shift
            ;;
        *)
            message="$1"
            shift
            ;;
    esac
done

if [[ -n "$sound_key" ]]; then
    if [[ -n "${sounds[$sound_key]}" ]]; then
        sound_file="$sound_dir/${sounds[$sound_key]}"
    else
        echo "Invalid sound key: $sound_key"
        sound_key=""
    fi
fi

# Resolve icon
if [[ -n "$icon_path" ]]; then
    if [[ "$icon_path" == "random" ]]; then
        if [[ -d "$random_icon_dir" ]]; then
            icon_path="$random_icon_dir/$(ls "$random_icon_dir" | shuf -n 1)"
        else
            echo "Random icon directory not found: $random_icon_dir"
            icon_path=""
        fi
    elif [[ ! -f "$icon_path" ]]; then
        # Try to find icon in icon_dir
        if [[ -f "$icon_dir/$icon_path" ]]; then
            icon_path="$icon_dir/$icon_path"
        else
            echo "Icon file not found: $icon_path"
            icon_path=""
        fi
    fi
fi

# Send the notification with extra notify-send options
if [[ -n "$icon_path" ]]; then
    eval notify-send -a "$app_name" -r "$replace_id" -u "$urgency" -i "$icon_path" $notify_extra_opts "\"$message\""
else
    eval notify-send -a "$app_name" -r "$replace_id" -u "$urgency" $notify_extra_opts "\"$message\""
fi

# Play sound
if [[ -n "$sound_file" && -f "$sound_file" ]]; then
    mpv --really-quiet "$sound_file" &
fi

